// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewgndsfgcvjovovspmrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Z25kc2ZnY3Zqb3ZvdnNwbXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTMyNzIsImV4cCI6MjA2MzkyOTI3Mn0.iuGniWdiKHQ5VSMNWsQw0hA1PiBOwkoR_NbHQef544w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);